[build]
command = "npm run build"
publish = "public"
functions = "netlify/functions"

[dev]
command = "npm run dev"
targetPort = 3000

# Set immutable caching for static files, because they have fingerprinted filenames
[[headers]]
for = "/build/*"

[headers.values]
"Cache-Control" = "public, max-age=31560000, immutable"